### PR TITLE
Format source files with pylama & black

### PR DESCRIPTION
**Pull request by hab6**
### Overview

Python code formatting tools `black` and `pylama` were used to format the Ingres connector source files.

Internal tracking [II-16370](https://actian.atlassian.net/browse/II-16370)

### Installed packages

    black             24.10.0
    pylama            8.4.1

### Documentation references
https://black.readthedocs.io/en/stable/index.html
https://klen.github.io/pylama/

### Notes on formatting

All formatting recommendations from running `black` were implemented.

Most formatting recommendations from running `pylama` were implemented. For each of the Ingres connector source files, only the following recommendations were _not_ implemented. This was my decision to not make the remaining shown changes. Feedback is welcome!

#### __init__.py

    __init__.py:7:1 W0611 'sqlalchemy_ingres.ingresdbi' imported but unused [pyflakes]
    __init__.py:13:1 W0611 '._version.__version__' imported but unused [pyflakes]

#### _version.py

_(All formatting recommendations were implemented)_

#### base.py

    base.py:45:101 E501 line too long (118 > 100 characters) [pycodestyle]
    base.py:86:101 E501 line too long (128 > 100 characters) [pycodestyle]
    base.py:191:101 E501 line too long (115 > 100 characters) [pycodestyle]
    base.py:204:101 E501 line too long (178 > 100 characters) [pycodestyle]
    base.py:205:101 E501 line too long (116 > 100 characters) [pycodestyle]
    base.py:250:5 C901 'IngresDDLCompiler.get_column_specification' is too complex (15) [mccabe]
    base.py:468:101 E501 line too long (165 > 100 characters) [pycodestyle]
    base.py:539:5 C901 'IngresDialect.get_columns' is too complex (11) [mccabe]

#### ingresdbi.py

    ingresdbi.py:17:101 E501 line too long (201 > 100 characters) [pycodestyle]

#### provision.py

_(All formatting recommendations were implemented)_

#### pyodbc.py
    pyodbc.py:24:101 E501 line too long (240 > 100 characters) [pycodestyle]
    pyodbc.py:57:101 E501 line too long (144 > 100 characters) [pycodestyle]
    pyodbc.py:67:101 E501 line too long (103 > 100 characters) [pycodestyle]

#### requirements.py

_(All formatting recommendations were implemented)_

#### zxjdbc.py

    zxjdbc.py:19:101 E501 line too long (201 > 100 characters) [pycodestyle]

#### setup.py

    setup.py:53:36 E0602 undefined name '__version__' [pyflakes]
    setup.py:57:13 E0602 undefined name '__version__' [pyflakes]
    setup.py:61:101 E501 line too long (126 > 100 characters) [pycodestyle]

### Comparison of SQLAlchemy test suite performance before and after code formatting changes

Ran the SQLAlchemy test suite versions 1.4.54 and 2.0.36 and concluded that there is no impact to the overall results compared to running the test suites with the original source files prior to reformatting with tools `black` and `pylama`.

### CODE REVIEW

**Comment by hab6** [comment]
Oops, forgot to format source file `setup.py`. Will do that and update with another commit.

**Comment by hab6** [comment]
Source file `setup.py` reformatted with `black` and `pylama` and changes committed to branch `hab6-lint-format`.

Ready for initial code review.

**Review by clach04 — COMMENTED** [review]
👍

**Comment by hab6** [comment]
@vsreeniv had a quick look at the proposed code changes and suggested that some of the formatting modifications to accommodate long lines with comments made the resulting code a little harder to read. I recall that @clach04 had also mentioned to watch for this type of thing before I ran the formatting tools.

Example 1
Reformatting-BasePY-Example1

Example 2
Reformatting-BasePY-Example2

I may end up reverting some of the formatting changes providing the original code doesn't blatantly violate PEP guidelines.

**Comment by hab6** [comment]
Ran the `black` linter again, this time using a line length of 110. The output looked good so I committed the subsequent files.

Also re-ran the dialect compliance suite with SQLAlchemy versions 1.4.54 and 2.0.36 and got good results.

Here are the best instances of the suite results with the latest (currently unmerged) commits in branch `hab6-lint-format`:

SQLAlchemy | Passed | Failed | Errors | Skipped | Total | Time
--|--|--|--|--|--|--
1.4.54 | 245 | 56 | 30 | 285 | 616 | 15.43s
2.0.36 | 554 | 94 | 33 | 882 | 1563 | 35.76s

**Comment by clach04** [comment]
> @vsreeniv had a quick look at the proposed code changes and suggested that some of the formatting modifications to accommodate long lines with comments made the resulting code a little harder to read. I recall that @clach04 had also mentioned to watch for this type of thing before I ran the formatting tools.
> 
> Example 1 Reformatting-BasePY-Example1
> 
> Example 2 Reformatting-BasePY-Example2
> 
> I may end up reverting some of the formatting changes providing the original code doesn't blatantly violate PEP guidelines.

Looking at https://github.com/ActianCorp/sqlalchemy-ingres/blob/hab6-lint-format/lib/sqlalchemy_ingres/base.py#L251 - looks like using 110 worked out well 👍

**Comment by hab6** [comment]
I'd like to merge this PR and follow with creating a new release of the Ingres connector.

Any other comments on the code formatting?

**Comment by clach04** [comment]
> I'd like to merge this PR and follow with creating a new release of the Ingres connector.
> 
> Any other comments on the code formatting?

None from me 👍 
CC @vsreeniv and @mianculovici

**Pull request merged**
